name: WordPress CI/CD Pipeline

on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  deploy:
      runs-on: ubuntu-latest
      needs: build
  
      steps:
        - name: SSH into DigitalOcean VM and deploy
          uses: appleboy/ssh-action@master
          with:
           host: ${{ secrets.DO_Host }}
           username: ${{ secrets.DO_User }}
           key: ${{ secrets.DO_SSH_}}
           script: |
            cd devops
            git pull origin main
            # Add any build or database migration steps here 
            sudo systemctl restart apache2
